
use nodes;


#[derive(Debug)]
enum AnyNode {
    ArrayExpression(nodes::ArrayExpression),
    AssignmentExpression(nodes::AssignmentExpression),
    BinaryExpression(nodes::BinaryExpression),
    BreakStatement(nodes::BreakStatement),
    CallExpression,
    ConstantLiteral,
    ConstAssignment,
    DebuggerStatement,
    DoWhileStatement,
    ExpressionStatement,
    ForInStatement,
    ForStatement,
    FunctionDeclaration,
    FunctionExpression,
    Identifier,
    IfStatement,
    IndexingExpression,
    ListExpression,
    LocalAssignmentExpression,
    LocalIdentifier,
    LocalUpdateExpression,
    LogicalExpression,
    MemberExpression,
    ObjectExpression,
    RootProgram,
    RegExpLiteral,
    ReturnStatement,
    SimpleForStatement,
    StatementList,
    SwitchStatement,
    TernaryExpression,
    ThisExpression,
    ThrowStatement,
    TryStatement,
    UnaryExpression,
    UnaryRefExpression,
    UpdateExpression,
    VoidExpression,
    WhileStatement,
    WithStatement,
    XMLConstantExpression,
    XMLDescendantsExpression,
    XMLPredicateExpression,
    XMLQualifiedNameExpression,
    XMLUnaryRefExpression,
}
