on:
  pull_request:
    branches: [master]

jobs:
  run-tests:
    name: Run Tests - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.13.1
        with:
          cmake-version: '3.25.2'

      - name: Configure CMake
        run: cmake .

      - name: Build Project
        run: cmake --build . --config debug

      - name: Run Tests
        run: ctest
